### ISSUE TITLE
Feature request: Whitelist or blacklist notebooks from search or query

### ISSUE THREAD

**Issue by az-pz** [Odotocodot/Flow.Launcher.Plugin.OneNote#13]
Having a lot of onenotes makes the search slow. Having an option to search in a particular notebook or removing certain notebooks from search through settings would be nice. I don't know enough c# to implement it myself.

**Comment by Odotocodot** [comment]
Hey Version 2.0 is just around the corner (soon<sup>TM</sup>), which should give a boost to performance! Hopefully this will help.

**Comment by az-pz** [comment]
Thanks for this plugin. Looking forward to the v2.0.
