### ISSUE TITLE
FEATURE REQUEST: Ability to write a quick note from within this plugin interface in Flow Launcher

### ISSUE THREAD

**Issue by Trubador** [Odotocodot/Flow.Launcher.Plugin.OneNote#20]
It could save me a lot of time if it was possible to write a short note from this OneNote plugin without having to open the OneNote interface. It would be nice if it looked a bit like this, so there would be a rich text editor on the right side of the interface for creating a new quick note and when I am done writing the note I can press CNTRL + S and it will be saved a new quick note in OneNote that I can review later: 
![image](https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote/assets/9870550/bba471be-625f-4186-a63b-9703d6078d0d)

**Comment by Odotocodot** [comment]
Ooh that a great idea!

Unfortunately I dont really have the time to add features currently, aside from a quick fix etc. (Was midway through a refactor with some icon updates, that i have had to put on hold 😢)
Feel free to make a pull request though, I will try to look at it if I have time!

**Comment by Trubador** [comment]
Thanks, I totally understand that you don't have much time to do it. I have this issue as well and especially writing code for the tool I am not sure how the structure is defined. I can help with testing out how the OneNote writing API works and give you that insight, but writing the code would be much faster if you could do.

**Comment by Odotocodot** [comment]
This has been implemented in version [2.1.0](https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote/releases/tag/v2.1.0) :)

**Comment by Trubador** [comment]
Thanks a lot mate 😀
