### ISSUE TITLE
Onenote Plugin Crash on every search

### ISSUE THREAD

**Issue by svensvond** [Odotocodot/Flow.Launcher.Plugin.OneNote#3]
Installed ON Version: 2301 Build 16026.20146
FlowLauncher: 1.13.0

Everytime i want to use the plugin it crashes. Log attached.
[2023-02-17.txt](https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote/files/10764001/2023-02-17.txt)

If that helps: function `rcntpgs:` works.

**Comment by Odotocodot** [comment]
Hmm it seems to be an issue with the library that I'm using, specifically when it calls onenote. It seems if onenote is '_busy_' a crash occurs. I have no idea what makes it busy or what busy is in this case.
Have you tried the good old uninstall and reinstall?
Also what version of onenote are you using 'OneNote' or 'OneNote for Windows 10'?

**Comment by svensvond** [comment]
![image](https://user-images.githubusercontent.com/37634123/219662581-f9dcdafb-fecb-4804-a130-c4621f9719ec.png)

**Comment by svensvond** [comment]
i had the uwp app removed .. if that is an issue.
I doubt that, since rcntpgs: works correctly

**Comment by Odotocodot** [comment]
Yeah "rcntpgs:" uses a different property to findpages in the library, hence why it might be working
I'm struggling to recreate the issue. Might be related to your build version of onenote.
Im guessing " nb:\ " doesnt work either?

**Comment by svensvond** [comment]
nope, crashs.

**Comment by svensvond** [comment]
![image](https://user-images.githubusercontent.com/37634123/219707153-4e6e13cb-5164-4cd8-a1e9-ba0022137e73.png)

**Comment by Odotocodot** [comment]
Was it ever working or has it always been crashing?

**Comment by svensvond** [comment]
yes, it did. Tried to reinstall office.

**Comment by Odotocodot** [comment]
So it was working 🤔, maybe an office update bugged it.
Did in reinstalling office fix it?
Heres a build that should log the error to log file: [OneNote-1.0.2-beta.zip](https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote/files/10771688/OneNote-1.0.2-beta.zip)

**Comment by svensvond** [comment]
ok, thanks .. now we are getting closer.
After removing and adding my notebook "default" the search worked again!
An exception is thrown when trying to open that notebook through nb:\\

[log.txt](https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote/files/10774354/log.txt)

**Comment by svensvond** [comment]
Update: 
The "default" notebook had a password protected section.
If i remove the password protected section, it works!!
So maybe the solution might be quite simple to skip those...

**Comment by Odotocodot** [comment]
Ah that explains why onenote was "busy"
Unfortunately the library used doesn't have a way of checking if a notebook is password protected.

**Comment by svensvond** [comment]
try catch and skip?

**Comment by Odotocodot** [comment]
Was thinking something like that, will get to it when I have time!

**Comment by Odotocodot** [comment]
Hey, I may have a fix for the encrypted section. Turns out there is a property for encryption! 
Will be pushing this build evetunally, but can you check if it works?
[OneNote-1.0.2-beta.zip](https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote/files/10833750/OneNote-1.0.2-beta.zip)

**Comment by jarusaurus** [comment]
thanks for the beta build. seems to work for me! had the same issue.
